#! /usr/bin/perl

use strict;
use warnings;

use Getopt::Long;
use POSIX qw( strftime mktime );
use Data::Dumper;

# inifinite snapshots for some filesystems

our %months=(Jan => 0,
             Feb => 1,
             Mar => 2,
             Apr => 3,
             May => 4,
             Jun => 5,
             Jul => 6,
             Aug => 7,
             Sep => 8,
             Oct => 9,
             Nov => 10,
             Dec => 11,
            );

our $DESTROY=1;
our $SNAP=1;

our %zfs=(
          'a-lnx010-pool/local'                => (365*2),
          'a-lnx010-pool/local/accx'           => (365*2),
          'a-lnx010-pool/local/accx/Downloads' => 10,
          'a-lnx010-pool/local/accx/Music'     => (365*3),
          'a-lnx010-pool/local/accx/MusicSync' => 10,
          'a-lnx010-pool/local/accx/Pictures'  => (365*3),
          'a-lnx010-pool/local/accx/df'        => (365*3),
          'a-lnx010-pool/local/accx/skyrim'    => 10
         );

GetOptions('snap!'    => \$SNAP,
           'destroy!' => \$DESTROY,
          );

my $time=strftime('%F%T',localtime(time()));
$time =~ s/[\:\-]//g;

while(my ($zfs,$days)=each(%zfs)) {
  if($DESTROY) {
    foreach(`/sbin/zfs list -t snapshot -o name,creation -s creation -r -H $zfs`) {
      chomp;
      my ($snap,$creation)=split(/\t/);
      next unless $snap =~ /^$zfs\@/;
      unless($creation =~ /\s+(\w\w\w)\s+(\d+)\s+(\d+)\:(\d+)\s+(\d\d\d\d)/) {
        die "unable to parse the date: $creation";
      }
      my $age=mktime(0,$4,$3,$2,$months{$1},($5-1900));
      #printf("%s\t%s\t%s\t%d\t%s\n",strftime('%F %T',localtime(time())),$creation,strftime('%F %T',localtime($age)),$days,strftime('%F %T',localtime($age + ($days * 24 * 60 * 60 ))));
      if(time() > ($age + ($days * 24 * 60 * 60 ))) {
        #printf("removing: %s created at %s\n",$snap,strftime('%F %T',localtime($age)));
        system("/sbin/zfs destroy $snap");
        if($? != 0) {
          warn("failed removing: %s created at %s\n",$snap,strftime('%F %T',localtime($age)));
          warn "failed command: /sbin/zfs destroy $snap";
        }
      }
    }
  }
  if($SNAP) {
    my $com="/sbin/zfs snapshot $zfs\@$time";
    system($com);
    if($? != 0) {
      warn "unable to create zfs snapshot for $zfs at $time";
      warn "failed command: $com";
    }
  }
}
