#! /bin/bash

com=/usr/bin/delta-dumper
if [[ ! -x $com ]]; then
    exit 0;
fi
t=$(mktemp)
$com --level critical --status-print > $t
if (( $( cat $t | wc -l ) > 0 )); then
    # uses | as a separator
    echo "<<<delta_dumper:sep(124)>>>"
    cat $t
fi
rm -f $t
