#! /bin/env perl

use strict;
use Backup::rdbduprunner;

if( -f '/var/lib/rdbduprunner/rdbduprunner.db' ) {
    print '<<<rdbduprunner:sep(60)>>>'."\n";
    Backup::rdbduprunner::create_dispatcher('rdbduprunner','daemon','error','/dev/null');
    Backup::rdbduprunner::status_print();
}
