#! /usr/bin/perl

use strict;
use warnings;
use Data::Dumper;
use POSIX qw(strftime);

my $LOGFILE='/var/log/rdbduprunner.log';
my $LOGPATTERN="${LOGFILE}[.-]%Y%m%d*";
my $MAXDAYS=31;

my @LOGFILES;
foreach my $day (0..$MAXDAYS) {
  push(@LOGFILES,glob(strftime($LOGPATTERN,localtime(time()-($day*24*60*60)))));
}

my %a;

foreach my $log (reverse(@LOGFILES)) {
  if($log =~ /\.gz/) {
    open(L,'gzip -d -c '.$log.'|') or warn "file ${log} exists but cannot be opened" and next;
  }
  else {
    open(L,'<'.$log) or warn "file ${log} exists but cannot be opened" and next;
  }
  while(<L>) {
    if (/msg=\"exit status\"/ and /rdbduprunner_tag=\"(.+?)\"/) {
      $a{$1} = $_;
    }
  }
  close(L);
}
if(scalar keys %a > 0) {
  print '<<<rdbduprunner>>>'."\n";
  print values %a;
}
